// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWDgWG7h6RgUWkLjlBbw_qw7EV7eOBPag',
    appId: '1:975435331702:web:922192cc5af00860fd8757',
    messagingSenderId: '975435331702',
    projectId: 'todolist-31cee',
    authDomain: 'todolist-31cee.firebaseapp.com',
    storageBucket: 'todolist-31cee.appspot.com',
    measurementId: 'G-EEFFNMHQK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoDSJZ09MQ58Phak_oGszrgT-5Gu1dpGI',
    appId: '1:975435331702:android:37d7012db329f7cefd8757',
    messagingSenderId: '975435331702',
    projectId: 'todolist-31cee',
    storageBucket: 'todolist-31cee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6wugyrB4ARzfL-qRl-rYOcJcLaztb2o',
    appId: '1:975435331702:ios:e4cdfc9f94acba86fd8757',
    messagingSenderId: '975435331702',
    projectId: 'todolist-31cee',
    storageBucket: 'todolist-31cee.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6wugyrB4ARzfL-qRl-rYOcJcLaztb2o',
    appId: '1:975435331702:ios:e4cdfc9f94acba86fd8757',
    messagingSenderId: '975435331702',
    projectId: 'todolist-31cee',
    storageBucket: 'todolist-31cee.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWDgWG7h6RgUWkLjlBbw_qw7EV7eOBPag',
    appId: '1:975435331702:web:f9aa60a5067fe3b3fd8757',
    messagingSenderId: '975435331702',
    projectId: 'todolist-31cee',
    authDomain: 'todolist-31cee.firebaseapp.com',
    storageBucket: 'todolist-31cee.appspot.com',
    measurementId: 'G-F6DSDC80BP',
  );
}
